version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "12:00"
      timezone: Europe/Moscow
    open-pull-requests-limit: 5
    labels:
      - dependencies
    assignees:
      - MarkDanilchenko
    ignore:
      - dependency-name: "zod"
      - dependency-name: "@anatine/zod-nestjs"
      - dependency-name: "@anatine/zod-openapi"
      - dependency-name: "@swc/cli"
      - dependency-name: "@nestjs/swagger"
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "zod"
          - "@anatine/zod-nestjs"
          - "@anatine/zod-openapi"
          - "@swc/cli"
          - "@nestjs/swagger"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      day: saturday
      time: "12:00"
      timezone: Europe/Moscow
    labels:
      - dependencies
    assignees:
      - MarkDanilchenko
    groups:
      actions:
        patterns:
          - "*"
