const REDIS_KEY_TTL_SEC: number = 60 * 60; // 1 hour;
const REDIS_KEY_MAX_BYTE_LEN: number = 1024; // 1 KB;
const REDIS_CLIENT = "REDIS_CLIENT";
const RMQ_MICROSERVICE = "RMQ_MICROSERVICE";

export { REDIS_KEY_TTL_SEC, REDIS_KEY_MAX_BYTE_LEN, REDIS_CLIENT, RMQ_MICROSERVICE };
