const REDIS_KEY_TTL_SEC = 60 * 60; // 1 hour;
const REDIS_KEY_MAX_BYTE_LEN = 1024; // 1 KB;
const REDIS_CLIENT = "REDIS_CLIENT";
const RMQ_MICROSERVICE = "RMQ_MICROSERVICE";
const CRON_USER_ANONYMIZATION_BATCH = 25;

export { REDIS_KEY_TTL_SEC, REDIS_KEY_MAX_BYTE_LEN, REDIS_CLIENT, RMQ_MICROSERVICE, CRON_USER_ANONYMIZATION_BATCH };
