import { MigrationInterface, QueryRunner, TableColumn } from "typeorm";

export class AddColumnsForEmailVerificationInAuthEntity1756647520693 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.addColumn(
      "authentications",
      new TableColumn({
        name: "isEmailVerified",
        type: "boolean",
        isNullable: false,
        default: false,
        comment: `email verification status`,
      }),
    );

    await queryRunner.addColumn(
      "authentications",
      new TableColumn({
        name: "emailVerificationToken",
        type: "varchar",
        isNullable: true,
        comment: `the email verification token, generated by the current web service`,
      }),
    );

    await queryRunner.addColumn(
      "authentications",
      new TableColumn({
        name: "emailVerificationSendAt",
        type: "timestamptz",
        isNullable: true,
        comment: `the time when the email verification token was sent during local email verification flow`,
      }),
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropColumn("authentications", "isEmailVerified");
    await queryRunner.dropColumn("authentications", "emailVerificationToken");
  }
}
