import { MigrationInterface, QueryRunner, Table, TableForeignKey } from "typeorm";

export class CreateAuthEntity1756644068516 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: "authentications",
        columns: [
          {
            name: "id",
            type: "uuid",
            isPrimary: true,
            isNullable: false,
            default: "uuid_generate_v4()",
          },
          {
            name: "userId",
            type: "uuid",
            isNullable: false,
          },
          {
            name: "provider",
            type: "varchar",
            isNullable: false,
          },
          {
            name: "refreshToken",
            type: "varchar",
            isNullable: true,
            comment: `the refresh token, generated by the current web service`,
          },
          {
            name: "password",
            type: "varchar",
            isNullable: true,
            comment: `the password of the authentication (only for local flow of authentication)`,
          },
          {
            name: "createdAt",
            type: "timestamptz",
            isNullable: false,
            default: "now()",
          },
          {
            name: "lastAccessedAt",
            type: "timestamptz",
            isNullable: false,
            default: "now()",
            comment: `the last time the authentication was accessed, similar to "updatedAt"`,
          },
        ],
      }),
      true, // if true, the table will be created if it does not exist;
    );

    await queryRunner.createForeignKey(
      "authentications",
      new TableForeignKey({
        columnNames: ["userId"],
        referencedColumnNames: ["id"],
        referencedTableName: "users",
        onDelete: "CASCADE",
      }),
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable(
      new Table({
        name: "authentications",
      }),
      true, // if true, the table will be dropped if it exists;
    );
  }
}
