name: GitHub Actions Main CI
run-name: "💾 CI on ${{ github.ref_name }}. Test suite (${{ github.event_name }})"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint-ts-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.4
        env:
          POSTGRES_USER: ${{ secrets.TEST_DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.TEST_DATABASE_NAME }}
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    strategy:
      matrix:
        node-version: [ 24.x ]

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event to ${{ github.ref_name }} branch."
      - run: echo "Author - ${{ github.actor }}"
      - run: echo "Commit message - ${{ github.event.head_commit.message }}"
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Create .env file for E2E tests in CI
        run: |
          echo "TEST_DATABASE_HOST=127.0.0.1" >> .env
          echo "TEST_DATABASE_PORT=5433" >> .env
          echo "TEST_DATABASE_USER=${{ secrets.TEST_DATABASE_USER }}" >> .env
          echo "TEST_DATABASE_PASSWORD=${{ secrets.TEST_DATABASE_PASSWORD }}" >> .env
          echo "TEST_DATABASE_NAME=${{ secrets.TEST_DATABASE_NAME }}" >> .env
          echo "NODE_ENV=test" >> .env
      - name: ESLint checks
        run: npm run lint:server
      - name: TS checks
        run: npm run tsc
      - name: Run Unit Tests (JEST)
        run: npm run test:unit

      - if: success()
        run: echo "✅ Job completed successfully!"
      - if: failure()
        run: echo "❌ Job failed!"
      - if: cancelled()
        run: echo "🚫 Job was cancelled!"
